blank_issues_enabled: true
contact_links:
  - name: Get in touch with the community
    url: https://discord.gg/rPWFv6W
    about: Hop on the Discord server if you want to discuss new features or problem with us
