{
  "env": {
    "browser": true,
    "jquery": true,
    "es6": true
  },
  "globals": {
    "d3": true,
    "MozActivity": true,
    "Sortable": true,
    "tinyMCE": true,
    "MG": true
  },
  "rules": {
    "func-names": [
      "error",
      "never"
    ],
    "no-unused-vars": [
      2,
      {
        "vars": "all",
        "varsIgnorePattern": "^wger"
      }
    ],
    "no-console": "off"
  }
}
